### PR TITLE
Update regions.md

### PR DESCRIPTION
**Pull request by civo-claire**
Add Product availability per region

### CODE REVIEW

**Comment by civo-claire** [comment]
@kaihoffman added the product available per region and the deep green bit - don't know how it renders as i don't have a local so hope the ticks and cross looks ok!

**Comment by kaihoffman** [comment]
@civo-claire they look like this!

Product availability screenshot

I also edited a typo (making Deep Green consistent) and added a plural to Database.

If it looks good to you, feel free to merge. I'll approve now.

**Review by kaihoffman — APPROVED** [review]

**Comment by civo-claire** [comment]
Thank you @kaihoffman and apologies for the various oversights! Do i squash and merge?

**Comment by kaihoffman** [comment]
Feel free @civo-claire !

**Pull request merged**
