### PR TITLE
Update commad to retrieve credentials 

### PR DESCRIPTION
**Pull request by s1ntaxe770r**
Noticed the  command to retrieve database credentials is `civo database credentials` as opposed to `civo database show --credentials`. I think the command might also be broken as using `civo database credentials [dbname]` returns an empty username and password. I have also observed the  same behavior  when trying to output credentials using the Terraform provider 

image

### CODE REVIEW

**Comment by s1ntaxe770r** [comment]
cc @kaihoffman

**Comment by alejandrojnm** [comment]
I will check this, but the last time I checked it works

**Comment by kaihoffman** [comment]
@s1ntaxe770r which version of the CLI are you using? I'm on Civo CLI v1.0.72 and my output looks different.

**Comment by s1ntaxe770r** [comment]
upgraded to v1.0.72 and it works now! Apologies for the false alarm

**Pull request closed without merging**
